---

- file:
    name: /hana
    state: directory
    owner: root
    group: root

- file:
    name: /hana/data
    state: directory
    owner: root
    group: root

- file:
    name: /hana/log
    state: directory
    owner: root
    group: root

- file:
    name: /hana/shared
    state: directory
    owner: root
    group: root

#### if install_nfs and ( unrar_cmd or  unrar_pkg) is set, unpack locally
- include: sap-unpack-media.yml
  when: not( (install_nfs is undefined) or (install_nfs is none) or (install_nfs | trim == '') )  and ( not( (unrar_cmd is undefined) or (unrar_cmd is none) or (unrar_cmd | trim == '')) or not ((unrar_pkg is undefined) or (unrar_pkg is none) or (unrar_pkg | trim == '') ) ) 

#### if install_nfs and no unrar* is set mount the installation dir
- include: sap-mount-media.yml
  when: not( (install_nfs is undefined) or (install_nfs is none) or (install_nfs | trim == '') )  and ( (unrar_cmd is undefined) or (unrar_cmd is none) or (unrar_cmd | trim == '') ) and  ( (unrar_pkg is undefined) or (unrar_pkg is none) or (unrar_pkg | trim == '') ) 

#### At this point the hana_installdir must be available ...
- file:
    name: "{{  hana_installdir }}"
    state: directory
    owner: root
    group: root

# Changed Thomas Bludau (20170508)
# Install directory could named completly different by hsr_name
# Use only hana_installdir for installation
# Otherwise you got problems while integrating on hsr_names side ...

- name: Get HANA Version Information
  shell:  awk ' ( $1 == "fullversion:" ) { print $2}'  "{{ hana_installdir }}"/DATA_UNITS/HDB_SERVER_LINUX_X86_64/server/manifest
  register: hana_version

- name: Make HANA Version persistent
  set_fact: 
    hana_version: hana_version.stdout
...
