---

- name: Set latest supported RedHat EUS release
  shell: subscription-manager release --set=7.2 
  register: rh_release
  changed_when: rh_release.rc == 0
  failed_when: rh_release.rc > 0
  when: ( ansible_distribution_version != 7.2 )


- name: ensure system has access to the right repos
  shell: "subscription-manager repos --enable={{ item }}"
  with_items:
    - rhel-7-server-eus-rpms
    - rhel-sap-hana-for-rhel-7-server-eus-rpms
  when: "repolist.stdout.find('{{ item }}') == -1"

...
